//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Sample.Templates {
    using System.Linq;
    using System;
    
    
    public partial class TextTemplate : TextTemplateBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 1 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("\r\n");
            
            #line default
            #line hidden
            
            #line 6 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("using System;\r\nusing System.Collections.Generic;\r\n\r\nnamespace ");
            
            #line default
            #line hidden
            
            #line 9 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( NameSpace ));
            
            #line default
            #line hidden
            
            #line 9 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("\r\n{\r\n");
            
            #line default
            #line hidden
            
            #line 11 "D:\github\T4Sample\Templates\TextTemplate.tt"
 if (!string.IsNullOrEmpty(Table.Description)) { 
            
            #line default
            #line hidden
            
            #line 12 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("    /// <summery>\r\n    /// ");
            
            #line default
            #line hidden
            
            #line 13 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Table.Description ));
            
            #line default
            #line hidden
            
            #line 13 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("\r\n    /// </summery>\r\n");
            
            #line default
            #line hidden
            
            #line 15 "D:\github\T4Sample\Templates\TextTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 16 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("    public class ");
            
            #line default
            #line hidden
            
            #line 16 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Table.Name ));
            
            #line default
            #line hidden
            
            #line 16 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("\r\n    {\r\n");
            
            #line default
            #line hidden
            
            #line 18 "D:\github\T4Sample\Templates\TextTemplate.tt"
 foreach (var x in Table.Columns) { 
            
            #line default
            #line hidden
            
            #line 19 "D:\github\T4Sample\Templates\TextTemplate.tt"
 if (!string.IsNullOrEmpty(x.Description)) { 
            
            #line default
            #line hidden
            
            #line 20 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("        /// <summery>\r\n        /// ");
            
            #line default
            #line hidden
            
            #line 21 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( x.Description ));
            
            #line default
            #line hidden
            
            #line 21 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("\r\n        /// </summery>\r\n");
            
            #line default
            #line hidden
            
            #line 23 "D:\github\T4Sample\Templates\TextTemplate.tt"
 } // End if 
            
            #line default
            #line hidden
            
            #line 24 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("        public ");
            
            #line default
            #line hidden
            
            #line 24 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( GetColumnType(x) ));
            
            #line default
            #line hidden
            
            #line 24 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 24 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( x.Name ));
            
            #line default
            #line hidden
            
            #line 24 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(" { get; ");
            
            #line default
            #line hidden
            
            #line 24 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( x.IsPrimary ? "" : "set; " ));
            
            #line default
            #line hidden
            
            #line 24 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("}\r\n\r\n");
            
            #line default
            #line hidden
            
            #line 26 "D:\github\T4Sample\Templates\TextTemplate.tt"
 } // End foreach 
            
            #line default
            #line hidden
            
            #line 27 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("        public ");
            
            #line default
            #line hidden
            
            #line 27 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Table.Name ));
            
            #line default
            #line hidden
            
            #line 27 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("(\r\n            ");
            
            #line default
            #line hidden
            
            #line 28 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( string.Join(",\n            ", Table.Columns.Where(x => x.IsPrimary).Select(d => $"{GetColumnType(d)} {d.Name}")) ));
            
            #line default
            #line hidden
            
            #line 28 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("\r\n        )\r\n        {\r\n");
            
            #line default
            #line hidden
            
            #line 31 "D:\github\T4Sample\Templates\TextTemplate.tt"
 foreach (var x in Table.Columns.Where(x => x.IsPrimary)) { 
            
            #line default
            #line hidden
            
            #line 32 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 32 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( x.Name ));
            
            #line default
            #line hidden
            
            #line 32 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(" = ");
            
            #line default
            #line hidden
            
            #line 32 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( x.Name ));
            
            #line default
            #line hidden
            
            #line 32 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(";\r\n");
            
            #line default
            #line hidden
            
            #line 33 "D:\github\T4Sample\Templates\TextTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 34 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("        }\r\n\r\n        public ");
            
            #line default
            #line hidden
            
            #line 36 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Table.Name ));
            
            #line default
            #line hidden
            
            #line 36 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("(\r\n            ");
            
            #line default
            #line hidden
            
            #line 37 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( string.Join(",\n            ", Table.Columns.Select(d => $"{GetColumnType(d)} {d.Name}")) ));
            
            #line default
            #line hidden
            
            #line 37 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("\r\n        )\r\n        {\r\n");
            
            #line default
            #line hidden
            
            #line 40 "D:\github\T4Sample\Templates\TextTemplate.tt"
 foreach (var x in Table.Columns) { 
            
            #line default
            #line hidden
            
            #line 41 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 41 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( x.Name ));
            
            #line default
            #line hidden
            
            #line 41 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(" = ");
            
            #line default
            #line hidden
            
            #line 41 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( x.Name ));
            
            #line default
            #line hidden
            
            #line 41 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write(";\r\n");
            
            #line default
            #line hidden
            
            #line 42 "D:\github\T4Sample\Templates\TextTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 43 "D:\github\T4Sample\Templates\TextTemplate.tt"
            this.Write("        }\r\n    }\r\n}\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class TextTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
